namespace: cisco
name: fmcansible
version: 0.1.0
readme: README.md

authors:
- joe Agster <joeaxcdw>
- Iurii Tymoshevskyi <itymo>
- Sameer Singh <sameesin>

description: An Ansible collection for managing Cisco Secure Firewall Management Center

license_file: 'LICENSE'

tags: 
  - "cisco"
  - "security"
  - "firewall"
  - "fmc"
  - "ftd"

dependencies: 
  community.general: 3.8.0
  community.network: 3.0.0
  ansible.netcommon: 3.0.1
  ansible.utils: 2.6.1

repository: https://github.com/CiscoDevNet/FMCAnsible
homepage: https://github.com/CiscoDevNet/FMCAnsible
issues: https://github.com/CiscoDevNet/FMCAnsible/issues

build_ignore: []