objects: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi:
    client:
      description: Internal client for FMC
      name: client
      version_added: 1.0.0
    fmc:
      description: HttpApi Plugin for Cisco Secure Firewall device
      name: fmc
      version_added: 1.0.0
  inventory: {}
  lookup: {}
  module:
    fmc_configuration:
      description: Manages configuration on Cisco FMC devices over REST API
      name: fmc_configuration
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 0.1.0
